### ISSUE TITLE
お店の口コミが取得できる

### ISSUE THREAD

**Issue by Marco3jp** [Marco3jp/graphql-server-sample#3]
- dataloader

**Comment by flum1025** [comment]
今の実装の課題

```graphql
query stores {
  stores {
    id
    name
    address
    reviews {
      id
      reviewText
    }
  }
}
```

こういうクエリを叩く場合、storeが100件あると

- storesを取得する処理でデータストアに1リクエスト
- それぞれのstoreごとのreviewsを取得する処理で100リクエスト

合計101回のリクエストが発生するのでN+1問題が出てくる。
数が増えれば増えるほどクエリの回数が増えるのでDBでもKVSでも負荷が増える。
また、ネットワークを経由してデータを取得することになるのでネットワークの通信コストも上がってしまう(遅延やデータ量等)

これを解決したい
